import type { CollectionConfig } from 'payload'
import { slug } from '@/fields/slug'

const LUCIDE_ICONS = [
  // Development
  { label: 'Code', value: 'Code' }, { label: 'Terminal', value: 'Terminal' },
  { label: 'Database', value: 'Database' }, { label: 'Server', value: 'Server' },
  { label: 'Cloud', value: 'Cloud' }, { label: 'Cpu', value: 'Cpu' },
  { label: 'Binary', value: 'Binary' }, { label: 'Braces', value: 'Braces' },
  { label: 'FileCode', value: 'FileCode' }, { label: 'FileCode2', value: 'FileCode2' },
  { label: 'FileTerminal', value: 'FileTerminal' }, { label: 'Layers', value: 'Layers' },
  { label: 'Package', value: 'Package' }, { label: 'Puzzle', value: 'Puzzle' },
  { label: 'Settings', value: 'Settings' }, { label: 'Settings2', value: 'Settings2' },
  { label: 'Wrench', value: 'Wrench' }, { label: 'Bug', value: 'Bug' },
  { label: 'Globe', value: 'Globe' }, { label: 'Globe2', value: 'Globe2' },
  { label: 'Network', value: 'Network' }, { label: 'Wifi', value: 'Wifi' },
  { label: 'HardDrive', value: 'HardDrive' }, { label: 'Monitor', value: 'Monitor' },
  { label: 'Laptop', value: 'Laptop' }, { label: 'Smartphone', value: 'Smartphone' },
  { label: 'Keyboard', value: 'Keyboard' }, { label: 'GitBranch', value: 'GitBranch' },
  { label: 'GitCommit', value: 'GitCommit' }, { label: 'GitFork', value: 'GitFork' },
  { label: 'GitMerge', value: 'GitMerge' }, { label: 'GitPullRequest', value: 'GitPullRequest' },
  { label: 'Github', value: 'Github' }, { label: 'Lock', value: 'Lock' },
  { label: 'Unlock', value: 'Unlock' }, { label: 'Shield', value: 'Shield' },
  { label: 'ShieldCheck', value: 'ShieldCheck' }, { label: 'Key', value: 'Key' },
  { label: 'Fingerprint', value: 'Fingerprint' }, { label: 'Zap', value: 'Zap' },
  { label: 'Activity', value: 'Activity' }, { label: 'BarChart', value: 'BarChart' },
  { label: 'BarChart2', value: 'BarChart2' }, { label: 'BarChart3', value: 'BarChart3' },
  { label: 'PieChart', value: 'PieChart' }, { label: 'LineChart', value: 'LineChart' },
  { label: 'TrendingUp', value: 'TrendingUp' }, { label: 'TrendingDown', value: 'TrendingDown' },
  { label: 'RefreshCw', value: 'RefreshCw' }, { label: 'RotateCw', value: 'RotateCw' },
  // Music & Audio
  { label: 'Music', value: 'Music' }, { label: 'Music2', value: 'Music2' },
  { label: 'Music3', value: 'Music3' }, { label: 'Music4', value: 'Music4' },
  { label: 'Headphones', value: 'Headphones' }, { label: 'Mic', value: 'Mic' },
  { label: 'Mic2', value: 'Mic2' }, { label: 'MicOff', value: 'MicOff' },
  { label: 'Radio', value: 'Radio' }, { label: 'Volume', value: 'Volume' },
  { label: 'Volume1', value: 'Volume1' }, { label: 'Volume2', value: 'Volume2' },
  { label: 'VolumeX', value: 'VolumeX' }, { label: 'Guitar', value: 'Guitar' },
  { label: 'Piano', value: 'Piano' }, { label: 'Drum', value: 'Drum' },
  { label: 'Disc', value: 'Disc' }, { label: 'Disc2', value: 'Disc2' },
  { label: 'Disc3', value: 'Disc3' }, { label: 'AudioWaveform', value: 'AudioWaveform' },
  { label: 'Waves', value: 'Waves' }, { label: 'Play', value: 'Play' },
  { label: 'Pause', value: 'Pause' }, { label: 'SkipBack', value: 'SkipBack' },
  { label: 'SkipForward', value: 'SkipForward' }, { label: 'Rewind', value: 'Rewind' },
  { label: 'FastForward', value: 'FastForward' }, { label: 'Repeat', value: 'Repeat' },
  { label: 'Shuffle', value: 'Shuffle' }, { label: 'ListMusic', value: 'ListMusic' },
  { label: 'Speaker', value: 'Speaker' }, { label: 'Sliders', value: 'Sliders' },
  // Art & Design
  { label: 'Palette', value: 'Palette' }, { label: 'Brush', value: 'Brush' },
  { label: 'Pen', value: 'Pen' }, { label: 'PenTool', value: 'PenTool' },
  { label: 'Pencil', value: 'Pencil' }, { label: 'Paintbrush', value: 'Paintbrush' },
  { label: 'Paintbrush2', value: 'Paintbrush2' }, { label: 'Feather', value: 'Feather' },
  { label: 'Crop', value: 'Crop' }, { label: 'Scissors', value: 'Scissors' },
  { label: 'Ruler', value: 'Ruler' }, { label: 'DraftingCompass', value: 'DraftingCompass' },
  { label: 'Image', value: 'Image' }, { label: 'ImagePlus', value: 'ImagePlus' },
  { label: 'Camera', value: 'Camera' }, { label: 'Aperture', value: 'Aperture' },
  { label: 'Film', value: 'Film' }, { label: 'Clapperboard', value: 'Clapperboard' },
  { label: 'Tv', value: 'Tv' }, { label: 'MonitorPlay', value: 'MonitorPlay' },
  { label: 'Frame', value: 'Frame' }, { label: 'Shapes', value: 'Shapes' },
  { label: 'Circle', value: 'Circle' }, { label: 'Triangle', value: 'Triangle' },
  { label: 'Hexagon', value: 'Hexagon' }, { label: 'Figma', value: 'Figma' },
  // Education & Research
  { label: 'Book', value: 'Book' }, { label: 'BookOpen', value: 'BookOpen' },
  { label: 'BookCopy', value: 'BookCopy' }, { label: 'BookMarked', value: 'BookMarked' },
  { label: 'GraduationCap', value: 'GraduationCap' }, { label: 'School', value: 'School' },
  { label: 'Microscope', value: 'Microscope' }, { label: 'FlaskConical', value: 'FlaskConical' },
  { label: 'TestTube', value: 'TestTube' }, { label: 'Brain', value: 'Brain' },
  { label: 'Lightbulb', value: 'Lightbulb' }, { label: 'LightbulbOff', value: 'LightbulbOff' },
  { label: 'Compass', value: 'Compass' }, { label: 'Map', value: 'Map' },
  { label: 'Award', value: 'Award' }, { label: 'Medal', value: 'Medal' },
  { label: 'Trophy', value: 'Trophy' }, { label: 'Target', value: 'Target' },
  { label: 'Atom', value: 'Atom' },
  // Social
  { label: 'Twitter', value: 'Twitter' }, { label: 'Instagram', value: 'Instagram' },
  { label: 'Linkedin', value: 'Linkedin' }, { label: 'Youtube', value: 'Youtube' },
  { label: 'Facebook', value: 'Facebook' }, { label: 'Discord', value: 'Discord' },
  { label: 'Slack', value: 'Slack' }, { label: 'Mail', value: 'Mail' },
  { label: 'MailOpen', value: 'MailOpen' }, { label: 'MessageCircle', value: 'MessageCircle' },
  { label: 'MessageSquare', value: 'MessageSquare' }, { label: 'Phone', value: 'Phone' },
  { label: 'PhoneCall', value: 'PhoneCall' }, { label: 'Video', value: 'Video' },
  { label: 'VideoOff', value: 'VideoOff' }, { label: 'Link', value: 'Link' },
  { label: 'Link2', value: 'Link2' }, { label: 'ExternalLink', value: 'ExternalLink' },
  { label: 'Share', value: 'Share' }, { label: 'Share2', value: 'Share2' },
  { label: 'Send', value: 'Send' }, { label: 'Rss', value: 'Rss' },
  { label: 'AtSign', value: 'AtSign' }, { label: 'Hash', value: 'Hash' },
  { label: 'User', value: 'User' }, { label: 'Users', value: 'Users' },
  { label: 'UserPlus', value: 'UserPlus' }, { label: 'UserCheck', value: 'UserCheck' },
  { label: 'Contact', value: 'Contact' },
  // RPG / Portfolio flavor
  { label: 'Sword', value: 'Sword' }, { label: 'ShieldAlert', value: 'ShieldAlert' },
  { label: 'Wand', value: 'Wand' }, { label: 'Wand2', value: 'Wand2' },
  { label: 'Sparkles', value: 'Sparkles' }, { label: 'Star', value: 'Star' },
  { label: 'Heart', value: 'Heart' }, { label: 'Flame', value: 'Flame' },
  { label: 'Crown', value: 'Crown' }, { label: 'Gem', value: 'Gem' },
  { label: 'Scroll', value: 'Scroll' }, { label: 'MapPin', value: 'MapPin' },
  { label: 'Navigation', value: 'Navigation' }, { label: 'Crosshair', value: 'Crosshair' },
  { label: 'Swords', value: 'Swords' }, { label: 'Ghost', value: 'Ghost' },
  // General/UI
  { label: 'Home', value: 'Home' }, { label: 'Layout', value: 'Layout' },
  { label: 'Grid', value: 'Grid' }, { label: 'List', value: 'List' },
  { label: 'Columns', value: 'Columns' }, { label: 'Sidebar', value: 'Sidebar' },
  { label: 'Menu', value: 'Menu' }, { label: 'Search', value: 'Search' },
  { label: 'Filter', value: 'Filter' }, { label: 'Download', value: 'Download' },
  { label: 'Upload', value: 'Upload' }, { label: 'Calendar', value: 'Calendar' },
  { label: 'Clock', value: 'Clock' }, { label: 'Timer', value: 'Timer' },
  { label: 'Bookmark', value: 'Bookmark' }, { label: 'Tag', value: 'Tag' },
  { label: 'Tags', value: 'Tags' }, { label: 'Flag', value: 'Flag' },
  { label: 'Bell', value: 'Bell' }, { label: 'Coffee', value: 'Coffee' },
  { label: 'Briefcase', value: 'Briefcase' }, { label: 'Building', value: 'Building' },
  { label: 'Building2', value: 'Building2' }, { label: 'Store', value: 'Store' },
  { label: 'DollarSign', value: 'DollarSign' }, { label: 'CreditCard', value: 'CreditCard' },
  { label: 'Infinity', value: 'Infinity' }, { label: 'Info', value: 'Info' },
  { label: 'HelpCircle', value: 'HelpCircle' }, { label: 'AlertTriangle', value: 'AlertTriangle' },
  { label: 'Eye', value: 'Eye' }, { label: 'EyeOff', value: 'EyeOff' },
  { label: 'Sun', value: 'Sun' }, { label: 'Moon', value: 'Moon' },
  { label: 'Wind', value: 'Wind' },
]

export const Quests: CollectionConfig = {
  slug: 'quests',
  labels: { singular: 'Quest', plural: 'Quests' },
  admin: {
    useAsTitle: 'title',
    group: 'Content',
    defaultColumns: ['title', 'category', 'questStatus', 'sortOrder', 'updatedAt'],
    description: 'Projects displayed as RPG quests.',
  },
  defaultSort: 'sortOrder',
  access: { read: () => true },
  versions: { drafts: true },
  fields: [
    slug('title'), // using our port of slug
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'sortOrder',
      type: 'number',
      required: true,
      defaultValue: 99,
      admin: {
        position: 'sidebar',
        description: 'Lower = appears first. 1=fjpp, 2=heionhub, 3=thesis, 4=Canadian College.',
      },
    },
    {
      name: 'featured',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        position: 'sidebar',
        description: 'Featured quests appear prominently in the grid.',
      },
    },
    {
      name: 'category',
      type: 'select',
      required: true,
      options: [
        { label: 'Tech', value: 'tech' },
        { label: 'Music', value: 'music' },
        { label: 'Art', value: 'art' },
        { label: 'Coffee', value: 'coffee' },
        { label: 'Education', value: 'education' },
      ],
    },
    {
      name: 'questStatus',
      type: 'select',
      required: true,
      defaultValue: 'completed',
      options: [
        { label: '✓ Completed', value: 'completed' },
        { label: '⟳ In Progress', value: 'in-progress' },
        { label: '◎ Side Quest', value: 'side-quest' },
      ],
    },
    {
      name: 'description',
      type: 'richText',
      required: true,
      localized: true,
    },
    {
      name: 'coverImage',
      type: 'upload',
      relationTo: 'media',
      admin: {
        description: 'Falls back to the default mockup image if not set.',
      },
    },
    {
      name: 'stack',
      type: 'array',
      label: 'Tech Stack',
      fields: [
        {
          name: 'techName',
          type: 'text',
          required: true,
          admin: { placeholder: 'e.g. Next.js, TypeScript' },
        },
        {
          name: 'icon',
          type: 'select',
          options: LUCIDE_ICONS,
          defaultValue: 'Code',
        },
      ],
    },
    {
      name: 'link',
      type: 'text',
      admin: {
        description: 'Live URL or GitHub link.',
        placeholder: 'https://...',
      },
    },
  ],
}
